apiVersion: v1 
kind: PersistentVolume 
metadata:  
  name: myshare
spec:  
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:    
    path: C/docker-share